from django.conf.urls import patterns, url

from cloudclass import views

urlpatterns = patterns(
    url(r'^$', views.dash_board, name='dash_board'),
    url(r'^dashboard/$', views.dash_board, name='dash_board'),
    url(r'^images/$', views.images, name='images'),
    url(r'^add_image_info/$', views.add_base_image_info, name='ajax_add_image_info'),
    url(r'^add_base_image/$', views.ajax_add_base_image, name='ajax_add_base_image'),
    url(r'^ajax_close_vm/$', views.ajax_close_vm, name='ajax_close_vm'),
    url(r'^ajax_publish_base_image/$', views.ajax_publish_base_image, name='ajax_publish_base_image'),
    url(r'^ajax_del_base_image/$', views.ajax_del_base_image, name='ajax_del_base_image'),
    url(r'^course/$', views.courses, name='courses'),

    url(r'^desktop/$', views.desktop_list, name='desktop_list'),
    url(r'^network/$', views.network_list, name='network_list'),

    url(r'^teacher/$', views.teacher_list, name='teacher_list'),
    url(r'^ajax_edit_teacher/$', views.ajax_edit_teacher, name='ajax_edit_teacher'),
    url(r'^ajax_add_teacher/$', views.ajax_add_teacher, name='ajax_add_teacher'),
    url(r'^ajax_del_teacher/$', views.ajax_del_teacher, name='ajax_del_teacher'),

    url(r'^ajaxdelbatchdesktop/$', views.ajaxdelbatch_desktop, name='ajaxdelbatch_desktop'),

    url(r'^ajaxgetisos/$', views.ajax_get_isos, name='ajax_get_isos'),
    url(r'^ajaxgetsofts/$', views.ajax_get_softs, name='ajax_get_softs'),
    url(r'^deleteiso/$', views.ajaxdel_iso, name='ajaxdel_iso'),
    url(r'^vnc/$', views.vnc_view, name='vnc_view'),
    url(r'^ajax_start_vnc/$', views.ajax_start_vnc, name='ajax_start_vnc'),
    url(r'^ajaxdelcourse/$', views.ajax_del_course, name='ajax_del_course'),
    url(r'^getmonitorinfo/$', views.ajax_get_host_monitor, name='ajax_get_host_monitor'),

    url(r'^ajaxaddnetwork/$', views.ajax_add_network, name="ajax_add_network"),
    url(r'^ajaxgetcourse/$', views.ajax_get_course, name='ajax_get_course'),
    url(r'^ajaxdelfile/$', views.ajax_del_file, name='ajax_del_file'),
    url(r'^changepwd/$', views.change_pwd, name='change_pwd'),
    url(r'^ajaxchangepwd/$', views.ajax_change_pwd, name='ajax_change_pwd'),
    url(r'^ajaxgetdashboard/$', views.ajax_get_dashboard, name='ajax_get_dashborad'),
    # url(r'^ajaxremovedisk/$', views.ajax_remove_disk, name='ajax_remove_disk'),
    url(r'^ajaxreboothost/$', views.ajax_reboot_host, name='ajax_reboot_host'),
    url(r'^ajaxshutoffhost/$', views.ajax_shutoff_host, name='ajax_shutoff_host'),
    url(r'^ajax_check_course_name/$', views.ajax_check_course_name, name='ajax_check_course_name'),
    url(r'^ajaxstartdhcp/$', views.ajax_start_dhcp_service, name='ajax_start_dhcp_service'),
    url(r'^ajaxstopdhcp/$', views.ajax_stop_dhcp_service, name='ajax_stop_dhcp_service'),
    url(r'^get_logs/$', views.get_logs, name='get_logs'),
    url(r'^logs/$', views.logs, name='logs'),
    url(r'^ajaxgetdesktops/$', views.ajax_get_desktops, name='ajax_get_desktops'),
    url(r'^sysupgrade/$', views.sys_upgrade, name='sys_upgrade'),
    url(r'^ajaxgetupgrades/$', views.ajax_get_upgrades, name='ajax_get_upgrades'),
    url(r'^ajaxdelupgrades/$', views.ajax_del_upgrades, name='ajax_del_upgrades'),
    url(r'^syssettings/$', views.sys_settings, name='sys_settings'),
    url(r'^ajaxinstallcastools/$', views.ajax_install_castools, name="ajax_install_castools"),
    url(r'^ajax_course_list/$',views.ajax_course_list, name="ajax_course_list"),
    url(r'^ajaxtopcourse/$',views.ajax_top_course, name="ajax_top_course"),

    url(r'^license/$', views.license, name='license'),
    url(r'^get_host_info/$', views.get_host_info, name='get_host_info'),
    url(r'^upload_license/$', views.upload_license, name='upload_license'),
    url(r'^operatevnc/$', views.vnc_operate, name='vnc_operate'),
    url(r'^ajaxvmoperate/$', views.ajax_vm_operate, name="ajax_vm_operate"),
    url(r'^init_guide/(?P<step>\d+)/$', views.init_guide, name='init_guide'),
    url(r'^stack_backends/$', views.stack_backends, name='stack_backends'),
    url(r'^ajax_set_host/$', views.set_host, name='set_host'),
    url(r'^param_set/$', views.param_set, name='param_set'),
    url(r'^ajax_reload_cas_settings/$', views.ajax_reload_cas_settings, name='ajax_reload_cas_settings'),
    url(r'^ajaxeditsettings/$', views.ajax_edit_settings, name='ajax_edit_settings'),

    url(r'^ajax_test_cas_connection/$', views.ajax_test_cas_connection, name='ajax_test_cas_connection'),
    url(r'^ajaxpptscreenshot/$', views.ajax_ppt_screenshot, name="ajax_ppt_screenshot"),

    url(r'^ajax_refresh_base_image/$', views.ajax_refresh_base_image, name='ajax_refresh_base_image'),
    url(r'^ajax_course_images/$', views.ajax_course_images, name='ajax_course_images'),
    url(r'^ajax_add_course_image/$',views.ajax_add_course_image, name='ajax_add_course_image'),
    url(r'^ajax_add_course_image_and_open/$', views.ajax_add_course_image_and_open, name='ajax_add_course_image_and_open'),
    url(r'^ajax_edit_course_image/$', views.ajax_edit_course_image, name='ajax_edit_course_image'),
    url(r'^ajax_get_os_version_by_image_id/$', views.ajax_get_os_version_by_image_id, name='ajax_get_os_version_by_image_id'),
    url(r'^ajax_base_image_list/$', views.ajax_base_image_list, name='ajax_base_image_list'),
    url(r'^ajax_get_course_pkgfiles/$', views.ajax_get_course_pkgfiles, name='ajax_get_course_pkgfiles'),
    url(r'^ajax_import_course/$', views.ajax_import_course, name='ajax_import_course'),
    url(r'^ajax_copy_base_image/$', views.ajax_copy_base_image, name='ajax_copy_base_image'),
    url(r'^ajax_edit_image_name/$',views.ajax_edit_image_name, name='ajax_edit_image_name'),
    url(r'^ajax_copy_course/$', views.ajax_copy_course, name='ajax_copy_course'),
    url(r'^grade_list/$', views.grade_list, name='grade_list'),
    url(r'^student_list/$', views.student_list, name='student_list'),
    url(r'^import_student_list/$', views.import_student_list, name='import_student_list'),
    url(r'^ajax_add_student/$', views.ajax_add_student, name='ajax_add_student'),
    url(r'^ajax_update_student/$', views.ajax_update_student, name='ajax_update_student'),
    url(r'^ajax_delete_student/$', views.ajax_delete_student, name='ajax_delete_student'),
    url(r'^ajax_get_student/$', views.ajax_get_student, name='ajax_get_student'),
    url(r'^ajax_update_password/$', views.ajax_update_password, name='ajax_update_password'),
    url(r'^ajax_add_gradeclass/$', views.ajax_add_gradeclass, name='ajax_add_gradeclass'),
    url(r'^ajax_get_gradeclass/$', views.ajax_get_gradeclass, name='ajax_get_gradeclass'),
    url(r'^ajax_delete_gradeclass/$', views.ajax_delete_gradeclass, name='ajax_delete_gradeclass'),
    url(r'^ajax_update_gradeclass/$', views.ajax_update_gradeclass, name='ajax_update_gradeclass'),
    url(r'^ajax_upload_csv/$', views.ajax_upload_csv, name='ajax_upload_csv'),
    url(r'^export_students_csv/$', views.export_students_csv, name='export_students_csv'),
)
