# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^get_courses/$', 'api.views.get_courses', name='get_courses'),
    url(r'^begin_course/$', 'api.views.begin_course', name='begin_course'),
    url(r'^finish_course/$', 'api.views.finish_course', name='finish_course'),
    url(r'^get_visitor/$', 'api.views.get_visitor', name='get_visitor'),
    url(r'^create_teacher_desktop/$', 'api.views.create_teacher_desktop', name='create_teacher_desktop'),
    url(r'^free_course/$', 'api.views.free_course', name='free_course'),
    url(r'^teacherlogin/$', 'api.views.ajax_teacher_login',
        name='ajax_teacher_login'),
    url(r'^teacherlogout/$', 'api.views.ajax_teacher_logout',
        name='ajax_teacher_logout'),
    url(r'^get_mac_map/$', 'api.views.get_mac_address_mapping',
        name='get_mac_address_mapping'),
    url(r'^get_terminals/$', 'api.views.get_terminal_list',
        name='get_terminal_list'),
    url(r'^get_network_state/$', 'api.views.get_network_state',
        name='get_network_state'),
    url(r'^control_network/$', 'api.views.control_desktop_network',
        name='control_desktop_network'),
    url(r'^revert_desktop/$', 'api.views.revert_desktop', name='revert_desktop'),
    url(r'^control_power/$', 'api.views.control_desktop_power',
        name='control_desktop_power'),
    url(r'^sort_terminals/$', 'api.views.sort_terminals', name='sort_terminals'),
    url(r'^clean_files/$','api.views.clean_files', name="clean_files"),
    url(r'^desktop_count/$', 'api.views.get_desktop_count', name='get_desktop_count'),
    url(r'^get_desktop_state/$', 'api.views.get_desktop_state', name='get_desktop_state'),
    url(r'^reset_desktop_state/$', 'api.views.reset_desktop_state', name='reset_desktop_state'),
    url(r'^get_gradeclass/$', 'api.views.get_gradeclass', name='get_gradeclass'),
    url(r'^get_studentslist/$', 'api.views.get_studentslist', name='get_studentslist'),
    url(r'^assign_to_student/$', 'api.views.assign_to_student', name='assign_to_student'),
    url(r'^verify_password/$', 'api.views.verify_password', name='verify_password'),
    url(r'^student_grade_vmnum/$', 'api.views.student_grade_vmnum', name='student_grade_vmnum'),
    url(r'^get_student_by_num/$', 'api.views.get_student_by_num', name='get_student_by_num'),
    url(r'^set_gradeclass_init/$', 'api.views.set_gradeclass_init', name='set_gradeclass_init'),
    url(r'make_symbolic_links/$', 'api.views.make_symbolic_links', name='make_symbolic_links'),
    url(r'delete_symbolic_links', 'api.views.delete_symbolic_links', name='delete_symbolic_links'),
)
